website-check example
vorteil/direktiv.github.io pull request #3
Opened 2021-06-27 23:07 UTC by jalfvort

Signed-off-by: Jon Alfaro <jon.alfaro@vorteil.io>

## Description

New example article added.

2021-06-27 23:52 UTC, jamesjmurtagh requested changes

2021-06-27 23:52 UTC, jamesjmurtagh commented on docs/examples/website-change.md
> +Here we are calling a HTTP `POST` request on the target website using our `vorteil/request:v5` direktiv app as a function. Since we only care about the `Last-Modified` and `Etag` headers we then extr
>  Here we are calling a HTTP `POST` request

I think it's more correct to say that you are performing a request, rather than calling it.

2021-06-27 23:52 UTC, jamesjmurtagh commented on docs/examples/website-change.md
> +Now that we both the current and previous header values we can make a comparison and check whether the website has changed using the switch state `check-site`.
> Now that we both ...

Now that we have?

2021-06-27 23:52 UTC, jamesjmurtagh commented on docs/examples/website-change.md
> +The switch state below has three possible conditions. The first condition is used for validation and will `transition` to the error state `unsupported-site` if neither `etag` or `lastModified` was fe
> If either one of these headers has changed ...

I *think* this should be "If either one of these headers **have** changed", but I'm not 100% sure of that. You might be right.

2021-06-27 23:52 UTC, jamesjmurtagh commented on docs/examples/website-change.md
> +Finally we save the current headers to the `lastModified` and `etag` workflow variables, so next time this workflow is executed they can retrived in the `get-old-headers` state.
> they can retrieved in the ...

"they can be retrieved" ?

2021-06-27 23:52 UTC, jamesjmurtagh commented on docs/examples/website-change.md
> +This workflow can currently run as is, and be manually executed. However this example is more than likely to be used as a [cron job](walkthrough/scheduling.html#cron). To convert this workflow all yo
> Below is an example that if added to the workflow, will run this workflow every once every two hours.

"Below is an example that, if added to the workflow, will run this workflow every once every two hours."

(added a comma)

2021-06-28 00:07 UTC, jalfvort commented
Issues addressed, Gracias

2021-06-28 00:11 UTC, merged